trigger:
- main

pool:
  name: Default  # your self-hosted agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'
  workingDirectory: '$(Build.SourcesDirectory)'

- script: npm test
  displayName: 'Run tests'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
